"""Data models for research projects."""

from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """Structured research plan generated by Research Manager."""
    
    question: str
    complexity: str = Field(description="Complexity level: simple, moderate, complex")
    research_goals: list[str]
    subquestions: list[str]
    expected_sources: list[str] = Field(description="Types of sources to search for")
    estimated_timeline: str
    research_strategy: str
    success_criteria: list[str]
    
    class Config:
        json_schema_extra = {
            "example": {
                "question": "Will AI replace software developers by 2030?",
                "complexity": "complex",
                "research_goals": [
                    "Understand current capabilities of AI coding systems",
                    "Analyze employment trends in software development",
                    "Identify limitations and barriers"
                ],
                "subquestions": [
                    "What can current AI coding systems actually do?",
                    "What evidence exists regarding developer productivity?",
                    "What are the limitations of AI coding systems?"
                ],
                "expected_sources": [
                    "Academic papers",
                    "Industry reports",
                    "Technical documentation"
                ],
                "estimated_timeline": "2-3 weeks",
                "research_strategy": "Multi-phase analysis",
                "success_criteria": ["At least 50 sources", "Analysis of conflicting views"]
            }
        }


class ResearchProject(BaseModel):
    """A research project document."""
    
    research_id: str
    question: str
    status: str = Field(description="planning|researching|reviewing|completed|monitoring")
    plan: Optional[ResearchPlan] = None
    created_at: datetime
    updated_at: datetime
    summary: Optional[str] = None
    confidence: Optional[str] = None
    monitoring_enabled: bool = False
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
